### ISSUE TITLE
Pregunta sobre algunas slides

### ISSUE THREAD

**Issue by merqurio** [victorvicpal/ML_CARDIOLOGIA_PyConES18#1]
Buenas Victor ! 

Lo primero, enhorabuena por la charla. No te puedes imaginar que rabia me da no haber podido estar ahí !
La verdad es que nosotros trabajamos con un proceso muy muy similar,  me ha servido para saber que soy el único del equipo que no conocía `imbalanced-learn` y lo hacia a mano 🙈 .

Tengo curiosidad por que explicaste en estas diapos:

<img width="1054" alt="screen shot 2018-10-09 at 14 48 48" src="https://user-images.githubusercontent.com/1485056/46670608-eb891380-cbd2-11e8-81ec-584130a3d6cb.png">

Creo que tengo una intuición, pero prefería preguntarte directamente. 
Gracias por tu tiempo ! 😁

**Comment by victorvicpal** [comment]
Hola @merqurio 
¡Tenemos que desvirtualizarnos ya! A ver si en Tarragona o en otro evento.
No te preocupes por la charla, seguramente puedas echarle un ojo cuando suban el vídeo (creo que en menos de un mes saldrá).

Esas diapos son un resumen de la idea que tuve para seleccionar variables biomédicas de carácter lineal para modelos de clasificación. Como trato mucho con variables continuas se me ocurrió proyectarlas en un tipo de PCA que se llama biplot en el cual obtienes dos matrices, una representa a los elementos **R** y otra a las variables **C**.

Lo que hago es evaluar una a una las variables y ver sobre las proyecciones de los elementos en ellas, aquellas que discriminan más. Con esta evaluación genero un ranking de variables con más peso.

La idea es sencilla. Tengo aún que darle una vuelta a ciertas cosas, crear un manual de uso y añadir un par de ejemplos.

Por ahora tengo parte del código en mi librería [biofes](https://github.com/victorvicpal/biofes)
